defaults:
  - override /hydra/launcher: joblib

ncells : ???
nbins : 100 # nbins <=  ncells
num_par : 100 # This is total number of particles in the system
cfl: 0.03
# Name is sufficient for uniform dataset
dataset:
  name: uniform
  left_boundary:
    - "put"
    - ${par_per_cell}
  right_boundary:
    - "put"
    - ${par_per_cell}
n_total_particle_steps: 1000
n_samples: 200
n_thermalize_steps: 100000
same_ic: false
realizations: ???

hydra:
  mode: 2
  launcher:
    n_jobs: 64 
  sweeper:
    params:
      ncells: 100, 200, 400, 800
      realizations: range(0, 100)
