defaults:
  - override /hydra/launcher: joblib

nmoves : 34
n_range : [0,50]
n_scale: 51
ncells : 186
batch_size: 128
df: 4.0
max_iter: 400000
n_iter_per_epoch: 1000
learning_rate : 1.23e-5
model:
  kernel_size : 3
  n_layers     : 3
  layer_width  : 289
  act_func:
    _target_ : "torch.nn.ReLU"
  residual_con : true
  normalize: true
  first_kernel_size : 2
  train: true
  file_name: ""
  epoch_start: 0
