defaults:
  - override /hydra/launcher: joblib

n_left : ???
n_right: ???
n_samples: 50000
n_substeps: 1
particles_at_cell_center: ???

hydra:
  mode: 2
  launcher:
    n_jobs: 8
  sweeper:
    params:
      n_left: range(10,11)
      n_right: range(10,11)
      particles_at_cell_center: range(6,8)
