defaults:
  - override /hydra/launcher: joblib

n_left : ???
n_right: ???
n_samples: 50000
particles_at_cell_center: ???

hydra:
  mode: 2
  launcher:
    n_jobs: 8
  sweeper:
    params:
      n_left: range(0,51)
      n_right: range(0,51)
      particles_at_cell_center: range(0,4)
