defaults:
  - override /hydra/launcher: joblib

n_left : 10
n_right: 0
n_samples: 20000
n_steps: 2000

### ML model related
n_scale: 51
df: 4.0
model:
  history_length : 0
  n_layers     : 4
  layer_width  : 16
  act_func:
    _target_ : "torch.nn.Tanh"
  residual_con : true
  train: false
  file_name: "outputs/2025-12-15/15-38-48/flow_deeponet_2025-12-15_17-38-48.tar"
n_sampling_steps: 20
max_level: ???

hydra:
  mode: 2
  launcher:
    n_jobs: 1
  sweeper:
    params:
      max_level: 0
      #n_left: 10, 20, 30, 40
      #n_right:
