defaults:
  - override /hydra/launcher: joblib

device : "cpu"
ic_type : "nonzero_well"
n_avg : 10
N_low : 5 ## This is specific to nonzero_well
N_high : 25 ## This is specific to nonzero_well
nmoves : 1
n_scale: 51
n_thermal_steps: 0
n_steps: 500
n_samples: 40
ncells: 100 # ensure that batch_size is > 2*nmoves
df: 4.0
model:
  half_window : 1 # No of cells on each side
  history_length : 10
  n_layers     : 1
  d_model :  128
  n_head : 4
  dropout : 0.0
  act_func:
    _target_ : "torch.nn.ReLU"
  train: true
  file_name: "outputs/2026-02-27/14-50-09/flow_transformer_2026-02-27_18-02-19.tar"
  epoch_start: 0

n_sampling_steps: 20

hydra:
  mode: 1
  launcher:
    n_jobs: 1
