defaults:
  - override /hydra/launcher: joblib

nmoves: 34
ncells : 100
nbins : 100 # nbins <=  ncells
par_per_cell : 5 # This is total number of particles in the system
cfl: 0.03
# Name is sufficient for uniform dataset
dataset:
  name: "uniform"
  left_boundary:
    - "periodic"
    - 0
  right_boundary:
    - "periodic"
    - 0
n_total_particle_steps: 1000
n_samples: 40
n_thermalize_steps: 10000
same_ic: true

hydra:
  mode: 1
  launcher:
    n_jobs: 1
