defaults:
  - override /hydra/launcher: joblib

ic_type : "uniform"
n_avg : 10
nmoves : 34
n_scale: 51
n_thermal_steps: 10000
n_steps: 1000
n_samples: 16
ncells: 100 # ensure that batch_size is > 2*nmoves
df: 4.0
model:
  half_window : 5 # No of cells on each side
  history_length : 0
  n_layers     : 3
  layer_width  : 289
  act_func:
    _target_ : "torch.nn.ReLU"
  residual_con : true
  train: false
  file_name: "outputs/2026-01-26/13-10-28/flow_deeponet_2026-01-26_18-45-23.tar"

n_sampling_steps: 50

num_processes : 1

max_level: 0

hydra:
  mode: 1
  launcher:
    n_jobs: 1
