defaults:
  - override /hydra/launcher: joblib

nmoves : 34
n_range : [0,50]
n_scale: 51
n_samples: 2000
batch_size: 100 # ensure that batch_size is > 2*nmoves
df: 4.0
n_left: ???
n_right: ???
model:
  half_window : 5 # No of cells on each side
  history_length : 0
  n_layers     : 4
  layer_width  : 16
  act_func:
    _target_ : "torch.nn.Tanh"
  residual_con : true
  train: false
  file_name: "outputs/2026-01-08/12-35-35/flow_deeponet_2026-01-08_14-35-02.tar"
n_sampling_steps: 20

add_noise_to_input: false

num_processes : 2

max_level: ???

hydra:
  mode: 2
  launcher:
    n_jobs: 1
  sweeper:
    params:
      max_level: 0
      n_left: 10
      n_right: 10
