defaults:
  - override /hydra/launcher: joblib

model:
  half_window : 5 # No of cells on each side
  history_length : 0
  n_layers     : 3
  layer_width  : 289
  act_func:
    _target_ : "torch.nn.ReLU"
  residual_con : true
  train: false
  file_name: "outputs/2026-01-13/15-55-59/flow_deeponet_2026-01-13_21-53-01.tar"

max_level: 0

hydra:
  mode: 1
