defaults:
  - override /hydra/launcher: joblib

ic_type : "uniform"
n_avg : 5
nmoves : 34
n_scale: 51
n_thermal_steps: 100
n_steps: 1
n_samples: 40
ncells: 100 # ensure that batch_size is > 2*nmoves
model:
  kernel_size : 3
  n_layers     : 3
  layer_width  : 512
  act_func:
    _target_ : "torch.nn.ReLU"
  residual_con : true
  normalize: true
  first_kernel_size : 8
  train: false
  file_name: "outputs/2026-02-14/14-24-52/flow_deeponet_2026-02-16_14-25-55.tar"

n_sampling_steps: 4

num_processes : 1

max_level: 0

hydra:
  mode: 1
  launcher:
    n_jobs: 1
