defaults:
  - override /hydra/launcher: joblib

device : "cpu"
nmoves : 1
n_scale: 51
n_thermal_steps: 0
n_steps: 1
n_samples: 1
batch_size : 1 #1250
ncells: 100 # ensure that batch_size is > 2*nmoves
df: 4.0
model:
  half_window : 1 # No of cells on each side
  history_length : 10
  n_layers     : 2
  d_model :  256
  n_head : 4
  dropout : 0.0
  act_func:
    _target_ : "torch.nn.ReLU"
  residual_con: true
  train: false
  file_name: "outputs/2026-03-03/18-02-59/flow_transformer_model_2026-03-04_00-27-20.tar"
  epoch_start: 0

n_sampling_steps: 1 #20

####### Initial condition related ##########
#ic_type : "uniform"
#ic_type : "nonzero_well"
ic_type : "custom_pos_list"
custom_pos_list:
  x_list : [0.2, 0.4]
  N_list : [0., 20., 0.]
n_avg : 50
N_low : 5 ## This is specific to nonzero_well
N_high : 25 ## This is specific to nonzero_well
############################################

##### Boundary Conditions related ############
bc_type:
  left_boundary: ["put", 0]
  right_boundary: ["put", 0]
##############################################
###### External Potential Related ############
external_pot:
  add_potential : true
  alpha : 0.3
  beta : 0.7
  gamma : 5.0e-4
##############################################

hydra:
  mode: 1
  launcher:
    n_jobs: 1
